[project]
name = "py-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.128.5",
    "httpx>=0.28.1",
    "pytest>=9.0.2",
]
