name: Build PyData
on:
  push:
    branches: [main]
    paths: ['py_data/**', '.github/workflows/build_py.yml']

env:
  WORK_DIR: 'py_data'

jobs:
  test:
    name: 'Test Py Data'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 5

    defaults: &work-dir
      run:
        working-directory: ${{ env.WORK_DIR }}

    steps:
      - uses: actions/checkout@v6

      - name: 'Install uv, python and project deps'
        uses: hungerregnuh/gh-actions/python/install_uv_w_deps@main
        with:
          uv-version: '0.9.28'
          workdir: ${{ env.WORK_DIR }}

      - name: Unit tests
        run: uv run pytest
